ShoppingList/ShoppingList/ViewModels/LoginViewModel.cs
namespace ShoppingList.ViewModels
{
    public class LoginViewModel
    {
      
        public int UserID { get; set; }    
        public string Email { get; set; }     
        public string Password { get; set; } 

    }
}

ShoppingList/ShoppingList/Controllers/LoginController.cs
using EntityLayer.Entities;
using EntityLayer.Context;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using ShoppingList.ViewModels;
using System.Diagnostics.Eventing.Reader;
using System.Security.Claims;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using NuGet.Common;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace ShoppingList.Controllers
{
    public class LoginController : Controller
    {
        ShoppingDbContext _context;


        public LoginController()
        {
           _context = new ShoppingDbContext();
        }

        
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            User user = _context.Users.Where(x => x.Email == model.Email && x.Password == model.Password).SingleOrDefault();

            if (ModelState.IsValid)
            {

                if (user != null)
                {
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name,user.UserName),
                        new Claim(ClaimTypes.Surname,user.UserSurname),
                        new Claim(ClaimTypes.Email,user.Email),
                        new Claim(ClaimTypes.Role,user.Role)

                    };

                    var claimsIdentity=new ClaimsIdentity(claims,CookieAuthenticationDefaults.AuthenticationScheme);
                    var authProperties=new AuthenticationProperties();
                   
                     await  HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,new ClaimsPrincipal(claimsIdentity),
                         authProperties);
                    
                    return RedirectToAction("List", "User", new { id = user.UserID });
                }

                ViewData["Login"] = "false";
                return View();
            }

            else
            {
                return View();
            }

        }


        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "Login");
        }

    }

}

ShoppingList/ShoppingList/Controllers/RegisterController.cs
using EntityLayer.Entities;
using EntityLayer.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShoppingList.ViewModels;

namespace ShoppingList.Controllers
{
    public class RegisterController : Controller
    {
        ShoppingDbContext context;
        public RegisterController() {
        context = new ShoppingDbContext();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(RegisterViewModel p)
        {
            if (ModelState.IsValid)
            {
                var login = context.Users.FirstOrDefault(x => x.Email == p.Email);

                if (login == null)
                {

                    User user = new User();
                    user.UserName = p.UserName;
                    user.UserSurname = p.UserSurname;
                    user.Email = p.Email;
                    user.Password = p.Password;
                    user.ConfirmPassword = p.ConfirmPassword;
                    user.Role = "User";
                    context.Users.Add(user);
                    context.SaveChanges();
                    return RedirectToAction("Login", "Login");

                }
                else
                {
                    ModelState.AddModelError("", "Sistemde bu mail ile kayıtlı bir kullanıcı bulunmaktadır.");
                }

            }
            else { return View(); }

            return View();
        }
    }
}

ShoppingList/ShoppingList/Views/Login/Login.cshtml
@{
    Layout = null;
}
@model LoginViewModel
<!DOCTYPE html>
<html lang="en">


@await Html.PartialAsync("~/Views/LayoutPartial/_HeadPartial.cshtml")

<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="content-wrapper d-flex align-items-center auth px-0">
                <div class="row w-100 mx-0">
                    <div class="col-lg-4 mx-auto">
                        <div class="auth-form-light text-left py-5 px-4 px-sm-5">
                            <div class="brand-logo text-center">
                                <img src="~/LogoImage/logo.png" alt="logo"  >
                            </div>
                            <h4>Merhaba! </h4>
                          
                            <h6 class="font-weight-light">Devam etmek için giriş yapın.</h6>
                            <form class="pt-3" method="post" action="Login">
                                <div class="form-group">
                                    <span asp-validation-for="@Model.Email" class="text-danger"></span>
                                    <input type="text" class="form-control form-control-lg" asp-for="@Model.Email" placeholder="Email">
                                </div>
                                <div class="form-group">
                                    <span asp-validation-for="@Model.Password" class="text-danger"></span>
                                    <input type="password" class="form-control form-control-lg" asp-for=@Model.Password placeholder="Şifre">
                                </div>
                                <div class="mt-3">
                                    <button class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" type="submit" >Giriş Yap</button>
                                </div>
                               
                                <div class="text-center mt-4 font-weight-light">
                                   Bir hesabın yok mu? @*<a href="~/Register/Register/" class="text-primary">Oluştur</a>*@
                                    @Html.ActionLink("Oluştur", "Register", "Register", null, new { @class = "text-primary" })
                                </div>
                                <br />
                                @{
                                    if (ViewData["Login"] != null)
                                    {
                                        <div><p class="text text-danger">Mail veya şifre yanlış.</p></div>
                                    }

                                }
                                <div class="text-danger" asp-validation-summary="ModelOnly">

                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- content-wrapper ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/skydash/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/skydash/js/off-canvas.js"></script>
    <script src="~/skydash/js/hoverable-collapse.js"></script>
    <script src="~/skydash/js/template.js"></script>
    <script src="~/skydash/js/settings.js"></script>
    <script src="~/skydash/js/todolist.js"></script>
    <!-- endinject -->
    @section Scripts{
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }
</body>

</html>