ShoppingList/ShoppingList/Controllers/UserController.cs
using EntityLayer.Context;
using EntityLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using ShoppingList.ViewModels;
using System.Net;
using System.Security.Claims;
using X.PagedList;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace ShoppingList.Controllers
{

    [Authorize(Roles = "User,Admin")]
    public class UserController : Controller
    {
        ShoppingDbContext context;
       
        public UserController()
        {
            context = new ShoppingDbContext();

        }



        [HttpGet]

        public IActionResult List(int id)
        {
            var user = context.Users.Where(x => x.UserID == id).SingleOrDefault();
            if (user != null)
            {
                UserListViewModel viewModel = new UserListViewModel();
                List<ListViewModel> shopList = context.ShopLists.Include(x => x.User).Where(x => x.User.UserID == id).Select(x => new ListViewModel()
                {
                    ListID = x.ListID,
                    ListName = x.ListName

                }).ToList();


                viewModel.UserID = id;
                viewModel.ListViewModel = shopList;


                return View(viewModel);
            }
            else
                return RedirectToAction("Error404", "ErrorPage");
 

        }



        [HttpGet]
        public IActionResult ListPost()
        {

            return View();
        }

        [HttpPost]
        public IActionResult ListPost(CreateListViewModel model, int id)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {

                // Var olan bir ShopList'i bulmaya çalış
                ShopList shopList = context.ShopLists.SingleOrDefault(x => x.ListName == model.ListName);

                // Eğer shopList değeri null değilse, yani aynı isimde bir liste varsa hata döndür
                if (shopList == null)
                {
                    // Aynı isimde bir liste yoksa, yeni bir ShopList oluştur ve kaydet
                    shopList = new ShopList()
                    {
                        ListName = model.ListName,
                        UserID = id
                    };
                    context.ShopLists.Add(shopList);
                    context.SaveChanges();
                    ViewData["ListPost"] = "true";
                    ModelState.Remove("ListName");
                    return View();


                }


                ViewData["NotListPost"] = "true";
                return View();
            }
        }


        public IActionResult ListDelete(int id)
        {
            ShopList shopList = context.ShopLists.SingleOrDefault(x => x.ListID == id);

            // Eğer shopList değeri null değilse, yani aynı isimde bir liste varsa hata döndür
            if (shopList == null)
            {
                return BadRequest("Bu isimde bir liste mevcut değil");
            }
            else
            {
                var userid = shopList.UserID;
                context.ShopLists.Remove(shopList);
                context.SaveChanges();
                UserListViewModel viewModel = new UserListViewModel();
                List<ListViewModel> modell = context.ShopLists.Include(x => x.User).Where(x => x.User.UserID == userid).Select(x => new ListViewModel()
                {
                    ListID = x.ListID,
                    ListName = x.ListName

                }).ToList();

                viewModel.UserID = userid;
                viewModel.ListViewModel = modell;

                return View("../User/List", viewModel);
            }
        }

        [HttpGet]
        public IActionResult ListDetail(int id,int page=1)
        {

            List<ListDetailViewModel> product = context.ListProductDetails.Include(x => x.Product).Where(x => x.ListID == id).Select(x => new ListDetailViewModel()
            {
                //    Description=x.Description,
                ProductName = x.Product.ProductName,
                Image = x.Product.Image
            }).ToList();

            if (product.Count == 0)
            { ViewData["NoProduct"] = "true"; }
            ViewBag.ListName = context.ShopLists.Where(x => x.ListID == id).Select(x => x.ListName).SingleOrDefault();


            TempData["ListId"] = id;
            TempData["ListId2"] = id;
            return View("../User/ListDetail", product);
        }




        void Get()
        {
            List<SelectListItem> selectList = new List<SelectListItem>();
            List<string> products = context.Products.Select(x => x.ProductName).ToList();
            foreach (var item in context.Products.Select(a => new { a.ProductID, a.ProductName }))
            {
                selectList.Add(new SelectListItem()
                {

                    Text = item.ProductName,
                    Value = item.ProductID.ToString()
                });
            }
            ViewBag.Products = products;
        }


        [HttpGet]
        public IActionResult ProductAdd()
        {
            Get();
            return View();
        }



        [HttpPost]
        public IActionResult ProductAdd(int id, ProductViewModel p)
        {
            if (ModelState.IsValid)
            {
                int productid = context.Products.Where(x => x.ProductName == p.ProductName).Select(x => x.ProductID).SingleOrDefault();
                ListProductDetail product = context.ListProductDetails.Where(x => x.ProductID == productid && x.ListID == id).SingleOrDefault();
                if (product == null)
                {
                    product = new ListProductDetail()
                    {

                        ListID = id,
                        ProductID = productid,                     
                        Description = p.ProductDescription

                    };
                    context.ListProductDetails.Add(product);
                    context.SaveChanges();
                    ViewData["ProductAdd"] = "true";
                    ModelState.Remove("ProductDescription");
                    Get();
                    return View();
                }
                else
                {
                    ViewData["NotListPost"] = "true";
                    Get();
                    ModelState.AddModelError("", "Listenizde bu ürün mevcut");
                    return View();
                }
            }
            else
            {
                Get();
                return View();
            }
        }



        public IActionResult ProductDelete(int id, string name)
        {


            ListProductDetail listProductDetail = new ListProductDetail();
            listProductDetail.ProductID = context.Products.Where(x => x.ProductName == name).Select(x => x.ProductID).SingleOrDefault();
            listProductDetail.ListID = id;
            //listProductDetail.Description = context.ListProductDetails.Where(x => x.ProductID == listProductDetail.ProductID && x.ListID == id).Select(x => x.Description).SingleOrDefault();

            context.ListProductDetails.Remove(listProductDetail);
            context.SaveChanges(true);

            List<ListDetailViewModel> product = context.ListProductDetails.Include(x => x.Product).Where(x => x.ListID == id).Select(x => new ListDetailViewModel()
            {
                //Description = x.Description,
                ProductName = x.Product.ProductName,
                Image = x.Product.Image
            }).ToList();
            TempData["ListId"] = id;
            return View("../User/ListDetail", product);
        }


        //[HttpGet("{id}/{name}")]

        [HttpGet]
        public IActionResult EditDescription(int id, string name)
        {
           
            var productid = context.Products.Where(x => x.ProductName == name).Select(x => x.ProductID).SingleOrDefault();
            ListProductDetail detail = context.ListProductDetails.Where(x => x.ListID == id && x.ProductID == productid).SingleOrDefault();
            
                if (detail.Description == null)
                    ViewBag.Description = "Ürün açıklaması ekleyebilirsiniz...";
                else
                    ViewBag.Description = detail.Description;

          
            return View(); 
        }

        //[HttpPost("{id}/{name}")]
        [HttpPost]
        public IActionResult EditDescription(int id, string name, EditDescriptionviewModel model)
        {
            if (ModelState.IsValid)
            {
                
                var productid = context.Products.Where(x => x.ProductName == name).Select(x => x.ProductID).SingleOrDefault();
                ListProductDetail detail = context.ListProductDetails.Where(x => x.ListID == id && x.ProductID == productid).SingleOrDefault();
                detail.Description = model.Description;

                ViewData["Edit"] = "true";
                context.Update(detail);
                context.SaveChanges();
                return View();
            }
            ModelState.Remove("Description");
            return View();
        }


        public IActionResult Shop(int id)
        {
            List<GoShopViewModel> product = context.ListProductDetails.Include(x => x.Product).Where(x => x.ListID == id).Select(x => new GoShopViewModel()
            {
                ProductID=x.ProductID,
                Description = x.Description,
                ProductName = x.Product.ProductName,
                Image = x.Product.Image
               

            }).ToList();

            if (product.Count == 0)
            { ViewData["NoProduct"] = "true"; }
            ViewBag.ListName = context.ShopLists.Where(x => x.ListID == id).Select(x => x.ListName).SingleOrDefault();


     

ShoppingList/ShoppingList/Views/LayoutPartial/_FooterPartial.cshtml
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">  © @DateTime.Now.Year. Tüm hakları saklıdır.</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Techcareer <i class="ti-heart text-danger ml-1"></i></span>
    </div>
</footer>

ShoppingList/ShoppingList/Views/LayoutPartial/_HeadPartial.cshtml
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Shopping List</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~vendors/mdi/css/materialdesignicons.min.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/favicon.png" />
</head>

ShoppingList/ShoppingList/Views/LayoutPartial/_NavbarPartial.cshtml
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo mr-5" href="~/skydash/index.html"><img src="~/LogoImage/logo.png" class="mr-2" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href="~/skydash/index.html"><img src="~/LogoImage/logomini.png" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="icon-menu"></span>
        </button>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
                <a class="dropdown-item" href="/Login/LogOut/">
                    <i class="ti-power-off text-primary"></i>
                    Çıkış Yap
                </a>

               
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="icon-menu"></span>
        </button>
    </div>
</nav>

ShoppingList/ShoppingList/Views/LayoutPartial/_SidebarPartial.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
      @*  <li class="nav-item">
            <a class="nav-link" asp-action="List" asp-controller="User" asp-route-id="(int)@TempData["ui"]">
                <i class="icon-paper menu-icon"></i>
                <span class="menu-title">Listelerim</span>
            </a>
        </li>*@
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
                <i class="icon-head menu-icon"></i>
                <span class="menu-title">Admin Paneli</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="auth">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a class="nav-link" asp-controller="Admin" asp-action="Product"> Ürünler </a></li>
                    <li class="nav-item"> <a class="nav-link" asp-controller="Admin" asp-action="Category"> Kategoriler </a></li>
                </ul>
            </div>
        </li>      
    </ul>
</nav>